# site setting
title: one
baseurl: /one
description: We help you get more leads by creating and managing high performing landing pages.
tagline: Get higher conversion rates on landing pages

#build setting
markdown: kramdown
  
exclude: ['README.md']
permalink: pretty #to remove .html

#sociallinks
facebook_username: crigroups
twitter_username: crigroups   
instagram_username: crigroups
youtube_username: crigroups



