# site setting
title: one
baseurl: /one
description: We help you get more leads by creating and managing high performing landing pages.
tagline: Get higher conversion rates on landing pages
heading: We give you increased results – every time!
sub-heading: Use our expertise to design effective landing pages. After we design and make your page, we help you optimize through A/B testing in order to make it perform to it’s max potential.
#build setting
markdown: kramdown
  
exclude: ['README.md']
permalink: pretty #to remove .html

#sociallinks
facebook_username: crigroups
twitter_username: crigroups   
instagram_username: crigroups
youtube_username: crigroups



