# site setting
title: one
baseurl: /one
tagline: 23 Yrs Experience in credit Repair. Pay only for credit deletion
description: I offer affordable and timely credit repair services. Please don't hesitate to contact me for a free consultation.
#banner
heading: We give you increased results – every time!
sub-heading: We Work extensively at repairing client's credit in order for them to be approved for a mortgage. We have a good relationship with affiliates such as realtors and loan officers to help turn our clients denied credit files into an approved credit file.
#about
about-title: Having 23+ Yrs experience in credit repir
about-content: I know exactly what a client needs when they come to my Credit Consulting Services and say they want to purchase a home but their credit profile is lacking. 
#contact
contact-title: Credit Repair Consultant
contact-desc: George is great with clients and explains the loan process to them in perfect detail. He goes the extra mile for each client and insures a timely closing. I highly recommend him to anyone needing a loan to buy a home or to refinance. 
contact-num: 6478794709
#build setting
markdown: kramdown
  
exclude: ['README.md']
permalink: pretty #to remove .html

#sociallinks
facebook_username: crigroups
twitter_username: crigroups   
instagram_username: crigroups
youtube_username: crigroups
google-plus_username: crigroups
gems:
  - jekyll-seo-tag
  - jekyll-sitemap


